name: Msrv

env:
  RUSTFLAGS: -Dwarnings
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse
  CARGO_UNSTABLE_SPARSE_REGISTRY: true

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'

jobs:
  msrv:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install rust 1.63
      run: |
        rustup toolchain install 1.63 nightly --no-self-update --profile minimal
        rustup default 1.63

    - name: Use minimal versions
      run: cargo +nightly update -Zminimal-versions

    - uses: Swatinem/rust-cache@v2
    - name: Check msrv
      run: cargo check --lib
